name: Sync Fork to Main Repo

on:
  workflow_dispatch:       # allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Git identity
        run: |
              git config --global user.name "Auto Sync Bot"
              git config --global user.email "autosync@github.com"

      - name: Add friend's fork as remote
        run: |
          git remote add friend https://github.com/vinit1221kumar/DLite-chatApp.git
          git fetch friend

      - name: Merge changes from friend's fork
        run: |
          git checkout main
          git merge friend/main --allow-unrelated-histories -X theirs

      - name: Push changes
        run: |
          git push origin main
